In [2]:
from tensorflow.keras.datasets import imdb

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train = pad_sequences(X_train, maxlen = 300)
X_test =  pad_sequences(X_test, maxlen = 300)

In [4]:
X_train.shape

(25000, 300)

In [5]:
X_test.shape

(25000, 300)

In [6]:
y_train.shape

(25000,)

In [7]:
y_test.shape

(25000,)

In [8]:
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [9]:
y_train[1]

np.int64(0)

In [10]:
word_index_dict = imdb.get_word_index()

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [11]:
for encoding in X_train[0]:
  for key, value in word_index_dict.items():
    if encoding == value:
      print(key, end = " ")

the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room and it so heart shows to years of every never going and help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but and to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other and in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of and odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but when from one bit then have tw

In [12]:
from sklearn.model_selection import train_test_split

# keep 9 samples for test, 400 for train (randomly sampled)
# first sample out a test set of size 9, then sample 400 from remaining for train
X_temp, X_test_T, y_temp, y_test_T = train_test_split(X_train, y_train, test_size=9, random_state=42, shuffle=True)
X_train_T, _, y_train_T, _ = train_test_split(X_temp, y_temp, train_size=400, random_state=42, shuffle=True)

print("train", X_train_T.shape, y_train_T.shape)
print("test",  X_test_T.shape,  y_test_T.shape)

train (400, 300) (400,)
test (9, 300) (9,)


In [13]:
y_train[0]

np.int64(1)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Flatten, Dense, TimeDistributed

model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 100, input_length = 300))
model.add(LSTM(64, activation = 'relu', return_sequences=True))

model.add(TimeDistributed(Dense(100)))

model.add(Flatten())
model.add(Dense(1024, activation = 'relu'))
model.add(Dense(512, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ ?                      │   0 (unbuilt) │
│ (TimeDistributed)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5, batch_size=128)

Epoch 1/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 600s 3s/step - accuracy: 0.6960 - loss: 0.5191 - val_accuracy: 0.8726 - val_loss: 0.3108
Epoch 2/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 554s 3s/step - accuracy: 0.9303 - loss: 0.1815 - val_accuracy: 0.8695 - val_loss: 0.3249
Epoch 3/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 563s 3s/step - accuracy: 0.9625 - loss: 0.1011 - val_accuracy: 0.8628 - val_loss: 0.3706
Epoch 4/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 543s 3s/step - accuracy: 0.9874 - loss: 0.0382 - val_accuracy: 0.8662 - val_loss: 0.6567
Epoch 5/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 572s 3s/step - accuracy: 0.9938 - loss: 0.0173 - val_accuracy: 0.8621 - val_loss: 0.6786


In [17]:
score = model.evaluate(X_test, y_test)
print("Loss: {}, Accuracy:{}".format(score[0], score[1]))

782/782 ━━━━━━━━━━━━━━━━━━━━ 82s 105ms/step - accuracy: 0.8641 - loss: 0.6642
Loss: 0.6786206960678101, Accuracy:0.8620799779891968


In [18]:
model.predict(X_test[0].reshape((1, 300)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[0.95040023]], dtype=float32)

In [22]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd


# Path to your zip file in Google Drive
path ='/content/drive/My Drive/Projects//NLP P2/'

df = pd.read_json(path + "Sarcasm_Headlines_Dataset.json", lines=True)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


is_sarcastic                                           headline  \
0             1  thirtysomething scientists unveil doomsday clo...   
1             0  dem rep. totally nails why congress is falling...   
2             0  eat your veggies: 9 deliciously different recipes   
3             1  inclement weather prevents liar from getting t...   
4             1  mother comes pretty close to using word 'strea...   

                                        article_link  
0  https://www.theonion.com/thirtysomething-scien...  
1  https://www.huffingtonpost.com/entry/donna-edw...  
2  https://www.huffingtonpost.com/entry/eat-your-...  
3  https://local.theonion.com/inclement-weather-p...  
4  https://www.theonion.com/mother-comes-pretty-c...

In [23]:
df = df.drop(['article_link'], axis=1)
df.head()

is_sarcastic                                           headline
0             1  thirtysomething scientists unveil doomsday clo...
1             0  dem rep. totally nails why congress is falling...
2             0  eat your veggies: 9 deliciously different recipes
3             1  inclement weather prevents liar from getting t...
4             1  mother comes pretty close to using word 'strea...

In [24]:
df['len'] = df['headline'].apply(lambda x: len(x.split(" ")))
df.head()

is_sarcastic                                           headline  len
0             1  thirtysomething scientists unveil doomsday clo...    8
1             0  dem rep. totally nails why congress is falling...   13
2             0  eat your veggies: 9 deliciously different recipes    7
3             1  inclement weather prevents liar from getting t...    8
4             1  mother comes pretty close to using word 'strea...    9

In [39]:
max_features = 10000
maxlen = 25
embedding_size = 100

In [40]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(df['headline']))
X = tokenizer.texts_to_sequences(df['headline'])

print("Number of Samples:", len(X))
print(X[0])

Number of Samples: 28619
[354, 3166, 7473, 2643, 2, 660, 1118]


In [41]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

X = pad_sequences(X, maxlen = maxlen)
y = np.asarray(df['is_sarcastic'])

print("Number of Labels: ", len(y))
print(y[0])

Number of Labels:  28619
1


In [42]:
tokenizer.word_index

{'to': 1,
 'of': 2,
 'the': 3,
 'in': 4,
 'for': 5,
 'a': 6,
 'on': 7,
 'and': 8,
 'with': 9,
 'is': 10,
 'new': 11,
 'trump': 12,
 'man': 13,
 'at': 14,
 'from': 15,
 'about': 16,
 'by': 17,
 'after': 18,
 'you': 19,
 'this': 20,
 'out': 21,
 'up': 22,
 'be': 23,
 'as': 24,
 'that': 25,
 'it': 26,
 'how': 27,
 'not': 28,
 'he': 29,
 'his': 30,
 'are': 31,
 'your': 32,
 'just': 33,
 'what': 34,
 'all': 35,
 'who': 36,
 'has': 37,
 'will': 38,
 'report': 39,
 'into': 40,
 'more': 41,
 'one': 42,
 'have': 43,
 'year': 44,
 'over': 45,
 'why': 46,
 'day': 47,
 'u': 48,
 'area': 49,
 'woman': 50,
 'can': 51,
 's': 52,
 'says': 53,
 'donald': 54,
 'time': 55,
 'first': 56,
 'like': 57,
 'no': 58,
 'her': 59,
 'get': 60,
 'off': 61,
 'old': 62,
 "trump's": 63,
 'life': 64,
 'now': 65,
 'people': 66,
 "'": 67,
 'an': 68,
 'house': 69,
 'still': 70,
 'obama': 71,
 'white': 72,
 'back': 73,
 'make': 74,
 'was': 75,
 'than': 76,
 'women': 77,
 'if': 78,
 'down': 79,
 'when': 80,
 'i': 81,
 'my':

In [43]:
num_words = len(tokenizer.word_index) + 1
print(num_words)

30885


In [44]:
glove_file =path + "glove.6B.100d.txt.zip"  #lets load the glove embeddings

In [45]:
from zipfile import ZipFile
with ZipFile(glove_file, 'r') as z:
  z.extractall()

In [46]:
EMBEDDING_FILE = './glove.6B.100d.txt'

embeddings = {}
for o in open(EMBEDDING_FILE):
    word = o.split(" ")[0]
    # print(word)
    embd = o.split(" ")[1:]
    embd = np.asarray(embd, dtype='float32')
    # print(embd)
    embeddings[word] = embd

# create a weight matrix for words in training docs
embedding_matrix = np.zeros((num_words, 100))

for word, i in tokenizer.word_index.items():
	embedding_vector = embeddings.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [47]:
len(embeddings.values())

400000

In [48]:
num_words

30885

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, Flatten

model = Sequential()
model.add(Embedding(num_words, embedding_size, weights = [embedding_matrix], input_length=maxlen))
model.add(Bidirectional(LSTM(128, return_sequences = True)))
model.add(Flatten())
model.add(Dense(40, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(20, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(1, activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [50]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [51]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │     3,088,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,088,500 (11.78 MB)

 Trainable params: 3,088,500 (11.78 MB)

 Non-trainable params: 0 (0.00 B)

In [52]:
batch_size = 100
epochs = 5

model.fit(X, y, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/5
229/229 ━━━━━━━━━━━━━━━━━━━━ 49s 184ms/step - accuracy: 0.6619 - loss: 0.5976 - val_accuracy: 0.8293 - val_loss: 0.3696
Epoch 2/5
229/229 ━━━━━━━━━━━━━━━━━━━━ 82s 185ms/step - accuracy: 0.8589 - loss: 0.3441 - val_accuracy: 0.8634 - val_loss: 0.3162
Epoch 3/5
229/229 ━━━━━━━━━━━━━━━━━━━━ 43s 190ms/step - accuracy: 0.9059 - loss: 0.2489 - val_accuracy: 0.8732 - val_loss: 0.3052
Epoch 4/5
229/229 ━━━━━━━━━━━━━━━━━━━━ 41s 179ms/step - accuracy: 0.9368 - loss: 0.1752 - val_accuracy: 0.8735 - val_loss: 0.3642
Epoch 5/5
229/229 ━━━━━━━━━━━━━━━━━━━━ 41s 178ms/step - accuracy: 0.9573 - loss: 0.1222 - val_accuracy: 0.8660 - val_loss: 0.4122


In [56]:
score = model.evaluate(X, y)
print("Loss: {}, Accuracy:{}".format(score[0], score[1]))

895/895 ━━━━━━━━━━━━━━━━━━━━ 22s 24ms/step - accuracy: 0.9727 - loss: 0.0850
Loss: 0.14552314579486847, Accuracy:0.9533876180648804


In [57]:
model.predict(X[2].reshape(1,25))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 410ms/step


array([[5.8532555e-06]], dtype=float32)